import Head from "next/head";
import React, { useState } from "react";
import Alert from "../../components/Alert";
import Drawer from "../../components/Drawer/Drawer";
import { APP_NAME } from "../../utils/helpers/constants/ConstantText";

export default function PagePhrases() {
  const [alertInfo, setAlertInfo] = useState(true);

  return (
    <>
      <Head>
        <title>Phrases - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer>
        <div className="flex flex-col p-2 lg:p-4 gap-y-4 flex-grow">
          {alertInfo && (
            <Alert
              color="info"
              title="Phrases page is used to manage phrases"
              subtitle={`Phrases are used for the user-end app to show expressions to users, e.g. Good Luck, Nice Try, Well done, etc. 
            Phrases mainly appear in pop-up messages when users start playing the game or when the game is over.`}
              action={() => setAlertInfo(false)}
              actionLabel="I understand"
            />
          )}
        </div>
      </Drawer>
    </>
  );
}
