type AnimationType = | "bounce"
    | "flash"
    | "pulse"
    | "rubberBand"
    | "shakeX"
    | "shakeY"
    | "headShake"
    | "swing"
    | "tada"
    | "wobble"
    | "jello"
    | "heartBeat"
    | "backInDown"
    | "backInLeft"
    | "backInRight"
    | "backInUp"
    | "backOutDown"
    | "backOutLeft"
    | "backOutRight"
    | "backOutUp"
    | "bounceIn"
    | "bounceInDown"
    | "bounceInLeft"
    | "bounceInRight"
    | "bounceInUp"
    | "bounceOut"
    | "bounceOutDown"
    | "bounceOutLeft"
    | "bounceOutRight"
    | "bounceOutUp"
    | "fadeIn"
    | "fadeInDown"
    | "fadeInDownBig"
    | "fadeInLeft"
    | "fadeInLeftBig"
    | "fadeInRight"
    | "fadeInRightBig"
    | "fadeInUp"
    | "fadeInUpBig"
    | "fadeInTopLeft"
    | "fadeInTopRight"
    | "fadeInBottomLeft"
    | "fadeInBottomRight"
    | "fadeOut"
    | "fadeOutDown"
    | "fadeOutDownBig"
    | "fadeOutLeft"
    | "fadeOutLeftBig"
    | "fadeOutRight"
    | "fadeOutRightBig"
    | "fadeOutUp"
    | "fadeOutUpBig"
    | "fadeOutTopLeft"
    | "fadeOutTopRight"
    | "fadeOutBottomRight"
    | "fadeOutBottomLeft"
    | "flip"
    | "flipInX"
    | "flipInY"
    | "flipOutX"
    | "flipOutY"
    | "lightSpeedInRight"
    | "lightSpeedInLeft"
    | "lightSpeedOutRight"
    | "lightSpeedOutLeft"
    | "rotateIn"
    | "rotateInDownLeft"
    | "rotateInDownRight"
    | "rotateInUpLeft"
    | "rotateInUpRight"
    | "rotateOut"
    | "rotateOutDownLeft"
    | "rotateOutDownRight"
    | "rotateOutUpLeft"
    | "rotateOutUpRight"
    | "hinge"
    | "jackInTheBox"
    | "rollIn"
    | "rollOut"
    | "zoomIn"
    | "zoomInDown"
    | "zoomInLeft"
    | "zoomInRight"
    | "zoomInUp"
    | "zoomOut"
    | "zoomOutDown"
    | "zoomOutLeft"
    | "zoomOutRight"
    | "zoomOutUp"
    | "slideInDown"
    | "slideInLeft"
    | "slideInRight"
    | "slideInUp"
    | "slideOutDown"
    | "slideOutLeft"
    | "slideOutRight"
    | "slideOutUp";
type AnimationSpeed = | "" | "slow" | "slower" | "fast" | "faster";
type AnimationHelperProp = {
    type: AnimationType;
    speed?: AnimationSpeed;
};
const PREFIX: string = "animatecss";

export const animate = (type:AnimationType,speed:AnimationSpeed =""): string => {
    const typeStr = `${PREFIX}-${type}`;
    const speedStr = speed === "" ? `` : `${PREFIX}-${speed}`;
    return `${PREFIX} ${typeStr} ${speedStr} `;
};