import Head from "next/head";
import Link from "next/link";
import React from "react";
import { APP_NAME } from "../utils/helpers/constants/ConstantText";
import {IoMdArrowRoundBack} from "react-icons/io";

export default function Custom404() {
  return (
    <div className="flex justify-center items-center min-h-screen flex-col">
      <Head>
        <title>404 Not Found - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="card w-fit bg-base-100 shadow-xl mx-4 border-error border-2">
        <div className="card-body justify-center items-center">
          <h1 className="text-9xl font-black text-error">404</h1>
          <h5 className="text-2xl text-error-content text-center mb-4">
            Page could not be found.
          </h5>
          <Link href="/" passHref replace>
            <button className="btn btn-outline"><IoMdArrowRoundBack size={24} className="mr-2"/>Back</button>
          </Link>
        </div>
      </div>
    </div>
  );
}
