import Head from "next/head";
import Link from "next/link";
import { NextRouter, useRouter } from "next/router";
import React from "react";
import { useCountContext } from "../utils/contexts/counter/CounterHooks";
import { useUiContext } from "../utils/contexts/ui/UiHooks";
// import { useTheme } from "next-themes";
// import { themeChange } from 'theme-change';

// const { themeChange } = require("theme-change");
export default function Dashboard() {
  const router: NextRouter = useRouter();
  // giving alias with colon (:)
  const { state: countState, action: countAction } = useCountContext();
  const { state: uiState, action: uiAction } = useUiContext();

  // const xd: boolean = false;
  // const {theme, setTheme} = useTheme();

  return (
    // <CounterProvider>
    <>
      <Head>
        <title>Dashboard - Scuffed Wordle API Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="drawer drawer-mobile w-full">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle btn" />
        <div className="drawer-content ">
          <div className="flex flex-col items-center justify-center">
            <label
              htmlFor="my-drawer-2"
              className="btn btn-primary drawer-button lg:hidden"
            >
              Open drawer
            </label>
            <Link href={"/"} passHref>
              <button className="btn btn-primary" onClick={() => router.back()}>
                Back
              </button>
            </Link>
            <h2>Counter</h2>
            <p>Count : {countState.count}</p>
            <button
              className="btn btn-primary"
              onClick={() => countAction.increase(1)}
            >
              Increase
            </button>
            <button
              className="btn btn-secondary"
              onClick={() => countAction.decrease(1)}
            >
              Decrease
            </button>

            <h2 className="mt-6">Dark theme : {uiState.darkTheme + ""}</h2>
            <input
              type="checkbox"
              className="toggle toggle-primary"
              checked={uiState.darkTheme}
              onChange={() => uiAction.toggleDarkTheme(!uiState.darkTheme)}
            />

            <div className="m-4">
              <button className="btn btn-primary">primary</button>
              <button className="btn btn-secondary">secondary</button>
              <button className="btn btn-accent">accent</button>
            </div>

            <div className="m-4" data-theme="valentine">
              <button className="btn btn-primary">primary</button>
              <button className="btn btn-secondary">secondary</button>
              <button className="btn btn-accent">accent</button>
            </div>

            <div className="m-4 tabs">
              <button className="tab tab-lifted">Tab 1</button>
              <button className="tab tab-lifted tab-active">Tab 2</button>
              <button className="tab tab-lifted">Tab 3</button>
            </div>

            <div className="m-4">
              <input type="checkbox" className="toggle toggle-primary" />
              <input type="checkbox" className="toggle toggle-secondary" />
              <input type="checkbox" className="toggle toggle-accent" />
            </div>

            <div className="card shadow-2xl w-80 m-4">
              <figure>
                <img src="https://picsum.photos/id/1005/500/250" />
              </figure>
              <div className="card-body">
                <h2 className="card-title">DaisyUi Card</h2>
                <p>
                  Rerum reiciendis beatae tenetur excepturi aut pariatur est
                  eos. Sit sit necessitatibus.
                </p>
              </div>
            </div>

            <div className="dropdown m-4">
              <div tabIndex={0} className="m-1 btn">
                Dropdown
              </div>
              <ul
                tabIndex={0}
                className="p-2 menu dropdown-content bg-neutral text-neutral-content rounded-box w-52"
              >
                <li>
                  <a>Item 1</a>
                </li>
                <li>
                  <a>Item 2</a>
                </li>
              </ul>
            </div>

            <label htmlFor="my-modal" className="btn modal-button">
              Modal
            </label>
            

            <ul className="steps my-4 w-full">
              <li className="step step-primary">Register</li>
              <li className="step step-primary">Choose plan</li>
              <li className="step">Purchase</li>
              <li className="step">Receive Product</li>
            </ul>

            <div className="avatar online m-10">
              <div className="rounded-full w-24 h-24">
                <img src="https://i.pravatar.cc/150?img=3" />
              </div>
            </div>
            <div className="avatar offline m-10">
              <div className="rounded-full w-24 h-24">
                <img src="https://i.pravatar.cc/150?img=3" />
              </div>
            </div>
          </div>
        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
          <ul className="menu p-4 overflow-y-auto w-80 bg-base-200 text-base-content">
            {/* <!-- Sidebar content here --> */}
            <li>
              <a className="bg-primary-focus">Sidebar Item 1</a>
            </li>
            <li>
              <a>Sidebar Item 2</a>
            </li>
          </ul>
        </div>
      </main>
      <input type="checkbox" id="my-modal" className="modal-toggle" />
            <div className="modal">
              <div className="modal-box">
                <p>
                  Enim dolorem dolorum omnis atque necessitatibus. Consequatur
                  aut adipisci qui iusto illo eaque. Consequatur repudiandae et.
                  Nulla ea quasi eligendi. Saepe velit autem minima.
                </p>
                <div className="modal-action">
                  <label htmlFor="my-modal" className="btn">
                    Close
                  </label>
                </div>
              </div>
            </div>
    </>
  );
}

// export default Dashboard;
