import Head from "next/head";
import { NextRouter, useRouter } from "next/router";
// import React, { useState } from "react";
// import { FiSun } from "react-icons/fi";
// import { MdMenu, MdOutlineDarkMode } from "react-icons/md";
// import { RiAppsFill } from "react-icons/ri";
import Drawer from "../components/Drawer/Drawer";
import {
  ID_MAIN_DRAWER,
  ID_MODAL_LOGOUT,
} from "../utils/helpers/constants/ConstantIds";
import { APP_NAME } from "../utils/helpers/constants/ConstantText";

// import { TiThMenu } from "react-icons/ti";
// import MenuItem from "../components/Drawer/MenuItem";
// import {
//   // APP_NAME,
//   LOGOUT_MODAL_DESC,
//   LOGOUT_MODAL_TITLE,
// } from "../utils/constants";
import { useCountContext } from "../utils/contexts/counter/CounterHooks";
import { useUiContext } from "../utils/contexts/ui/UiHooks";
// import { useTheme } from "next-themes";
// import { themeChange } from 'theme-change';

// const { themeChange } = require("theme-change");
export default function Dashboard() {
  const router: NextRouter = useRouter();
  // giving alias with colon (:)
  const { state: countState, action: countAction } = useCountContext();
  const { state: uiState, action: uiAction } = useUiContext();

  return (
    // <CounterProvider>
    <>
      <Head>
        <title>Dashboard - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer>
        {/* CONTENT */}
        <div className="flex flex-col items-center justify-center p-2 lg:p-4">
          <label
            htmlFor={ID_MAIN_DRAWER}
            className="btn btn-primary drawer-button lg:hidden"
          >
            Open drawer
          </label>
          {/* <Link href={"/"} passHref> */}
          <button
            className="btn btn-primary"
            onClick={() => router.replace("/")}
          >
            Back
          </button>
          {/* </Link> */}
          <h2>Counter</h2>
          <p>
            Count :
            <span
              key={countState.count}
              className="animated-faster animated animated-rotateIn"
            >
              {countState.count}
            </span>
          </p>
          <button
            className="btn btn-primary"
            onClick={() => countAction.increase(1)}
          >
            Increase
          </button>
          <button
            className="btn btn-secondary"
            onClick={() => countAction.decrease(1)}
          >
            Decrease
          </button>

          <h2 className="mt-6">Dark theme : {uiState.darkTheme + ""}</h2>
          <input
            type="checkbox"
            className="toggle-primary toggle"
            checked={uiState.darkTheme}
            onChange={() => uiAction.toggleDarkTheme()}
          />

          <div className="m-4">
            <button className="btn btn-primary">primary</button>
            <button className="btn btn-secondary">secondary</button>
            <button className="btn btn-accent">accent</button>
          </div>

          <div className="m-4" data-theme="valentine">
            <button className="btn btn-primary">primary</button>
            <button className="btn btn-secondary">secondary</button>
            <button className="btn btn-accent">accent</button>
          </div>

          <div className="tabs m-4">
            <button className="tab tab-lifted">Tab 1</button>
            <button className="tab tab-lifted tab-active">Tab 2</button>
            <button className="tab tab-lifted">Tab 3</button>
          </div>

          <div className="m-4">
            <input type="checkbox" className="toggle-primary toggle" />
            <input type="checkbox" className="toggle-secondary toggle" />
            <input type="checkbox" className="toggle-accent toggle" />
          </div>

          <div className="card m-4 w-80 shadow-2xl">
            <figure>
              <img src="https://picsum.photos/id/1005/500/250" />
            </figure>
            <div className="card-body">
              <h2 className="card-title">DaisyUi Card</h2>
              <p>
                Rerum reiciendis beatae tenetur excepturi aut pariatur est eos.
                Sit sit necessitatibus.
              </p>
            </div>
          </div>

          <div className="dropdown m-4">
            <div tabIndex={0} className="btn m-1">
              Dropdown
            </div>
            <ul
              tabIndex={0}
              className="dropdown-content menu rounded-box w-52 bg-neutral p-2 text-neutral-content"
            >
              <li>
                <a>Item 1</a>
              </li>
              <li>
                <a>Item 2</a>
              </li>
            </ul>
          </div>

          <label htmlFor={ID_MODAL_LOGOUT} className="modal-button btn">
            Modal
          </label>

          <ul className="steps my-4 w-full">
            <li className="step-primary step">Register</li>
            <li className="step-primary step">Choose plan</li>
            <li className="step">Purchase</li>
            <li className="step">Receive Product</li>
          </ul>

          <div className="online avatar m-10">
            <div className="h-24 w-24 rounded-full">
              <img src="https://i.pravatar.cc/150?img=3" />
            </div>
          </div>
          <div className="avatar offline m-10">
            <div className="h-24 w-24 rounded-full">
              <img src="https://i.pravatar.cc/150?img=3" />
            </div>
          </div>
        </div>
      </Drawer>
    </>
  );
}

// export default Dashboard;
