import Head from "next/head";
import { NextRouter, useRouter } from "next/router";
import React from "react";
import Drawer from "../components/Drawer/Drawer";
import { ID_MAIN_DRAWER } from "../utils/constants/ConstantIds";
import { APP_NAME } from "../utils/constants/ConstantText";
import { useCountContext } from "../utils/contexts/counter/CounterHooks";
import { useUiContext } from "../utils/contexts/ui/UiHooks";

export default function Dashboard() {
  const router: NextRouter = useRouter();
  // giving alias with colon (:)
  const { state: countState, action: countAction } = useCountContext();
  const { state: uiState, action: uiAction } = useUiContext();

  return (
    // <CounterProvider>
    <>
      <Head>
        <title>Games - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer>
        {/* CONTENT */}
        <div className="flex flex-col items-center justify-center p-2 lg:p-4">
          <label
            htmlFor={ID_MAIN_DRAWER}
            className="btn btn-primary drawer-button lg:hidden"
          >
            Open drawer
          </label>
        </div>
      </Drawer>
    </>
  );
}

// export default Dashboard;
