import { nanoid } from "nanoid";
import Head from "next/head";
import { NextRouter, useRouter } from "next/router";
import React, { useEffect } from "react";
import { IoMdAddCircleOutline } from "react-icons/io";
import { MdClose, MdDelete, MdEdit } from "react-icons/md";
import Drawer from "../components/Drawer/Drawer";
import Modal from "../components/Modal";
// import { ID_MAIN_DRAWER } from "../utils/constants/ConstantIds";
import { APP_NAME } from "../utils/constants/ConstantText";
import { useGameContext } from "../utils/contexts/game/GameHooks";
import { generateGameData } from "../utils/contexts/game/GameProvider";
import { useUiContext } from "../utils/contexts/ui/UiHooks";
// import { useCountContext } from "../utils/contexts/counter/CounterHooks";
// import { useUiContext } from "../utils/contexts/ui/UiHooks";

export default function Dashboard() {
  const router: NextRouter = useRouter();
  // giving alias with colon (:)
  // const { state: countState, action: countAction } = useCountContext();
  const { state: uiState, action: uiAction } = useUiContext();

  useEffect(() => {
    if (uiState.menuOn !== "games") {
      uiAction.selectMenu("games");
    }
  });

  const { state: gameState, action: gameAction } = useGameContext();
  const gameList = gameState.list;

  function getId(): string {
    const newId = nanoid();
    if (gameList.map((game) => game.id).includes(newId)) return getId();
    return newId;
  }

  function addGame() {
    gameAction.add(generateGameData(getId()));
  }
  function deleteGame(gameId: string) {
    gameAction.delete(gameId);
  }

  return (
    // <CounterProvider>
    <>
      <Head>
        <title>Games - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer>
        {/* CONTENT */}
        <div className="flex flex-col p-2 lg:p-4 gap-y-4">
          <div className="flex flex-wrap items-center gap-4">
            <button
              // htmlFor={ID_MAIN_DRAWER}
              className="btn btn-primary gap-2 lg:btn-lg btn-md"
              onClick={() => addGame()}
            >
              ADD GAMES ({gameList.length})
              <IoMdAddCircleOutline size={30} />
            </button>
            <label
              htmlFor="games-clearall-modal"
              className="btn btn-error gap-2 lg:btn-lg btn-md"
            >
              CLEAR ALL
              <MdClose size={30} />
            </label>
            {/* MODAL */}
            <input
              type="checkbox"
              id="games-clearall-modal"
              className="modal-toggle"
            />
            <Modal
              id="games-clearall-modal"
              title="Clear All Game Data"
              desc="All game data will be wiped out. This action cannot be undone. Use it wisely!"
              color="error"
              actionY={() => gameAction.clear("")}
            />
          </div>
          <div className="flex flex-wrap justify-center gap-4">
            {gameList.map((game, index) => (
              <div
                key={game.id}
                className="card card-compact shadow-lg outline outline-1 outline-primary animatecss animatecss-flipInY"
              >
                <h2 className="card-title p-4 bg-primary">{game.name}</h2>
                <div className="card-body">
                  <p>{game.matrix}</p>
                  <div className="card-actions justify-end">
                    <button
                      key={"btn-game-item-edit-" + index}
                      className="btn btn-sm btn-circle"
                      // onClick={() => deleteGame(game.id)}
                    >
                      <MdEdit size={18} />
                    </button>
                    <button
                      key={"btn-game-item-delete-" + index}
                      className="btn btn-sm btn-circle btn-error"
                      onClick={() => deleteGame(game.id)}
                    >
                      <MdDelete size={18} />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </Drawer>
    </>
  );
}

// export default Dashboard;
