import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FaRegArrowAltCircleRight } from "react-icons/fa";
import { APP_NAME } from "../utils/constants/ConstantText";

const Home: NextPage = () => {
  return (
    <div className="flex justify-center items-center min-h-screen flex-col">
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my">
        <div className="card min-w-fit h-auto bg-base-100 shadow-xl border border-primary m-2">
          <figure className="px-10 pt-10">
            <img src="/vercel.svg" alt="icon" />
          </figure>
          <div className="card-body items-center text-center">
            {/* <h2 className="card-title">Shoes!</h2> */}
            <input
              type="text"
              placeholder="Username"
              className="input input-bordered w-full max-w-xs" />
            <input
              type="password"
              placeholder="Password"
              className="input input-bordered w-full max-w-xs" />
            <Link href="/dashboard" passHref>
              <button className="btn btn-primary w-full">
                Login
                <FaRegArrowAltCircleRight size={24} className="ml-2" />
              </button>
            </Link>

            {/* <div className="card-actions">
            </div> */}
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Powered by{' '}
                <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              </a>
            </footer> */}
    </div>
  );
};

export default Home;
