import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FaRegArrowAltCircleRight } from "react-icons/fa";
import { MdAlternateEmail } from "react-icons/md";
import { GoKey } from "react-icons/go";
import { APP_NAME } from "../utils/helpers/constants/ConstantText";

const Home: NextPage = () => {
  return (
    <div
      className="flex justify-center items-center min-h-screen flex-col bg-base-300 bg-pattern"
      style={{
        // backgroundImage: `url("${"/pattern.svg"}")`,
        // eslint-disable-next-line max-len
        // backgroundColor: `#DFDBE5`,
        // eslint-disable-next-line max-len
        // backgroundImage: `url(/terrazzo.svg)`,
      }}
    >
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full justify-center">
        <div className="bg-base-300 sm:max-w-xl rounded-lg w-full">
          <div
            className={`card h-auto bg-base-100 rounded-none text-center
            sm:m-4 sm:rounded-lg
            animatecss animatecss-jackInTheBox animatecss-faster
            `}
          > 
            <figure className="p-4">
              <img src="/icon.png" alt="icon" height={120} width={120} />
            </figure>
            <h2 className="text-2xl font-bold">{APP_NAME}</h2>
            <div className="card-body items-center text-center gap-4 p-4 sm:p-8">
              {/* <h2 className="card-title">Shoes!</h2> */}

              <div className="form-control w-full">
                <label className="input-group lg:input-group-lg input-group-md">
                  <span>
                    <MdAlternateEmail size={30} />
                  </span>
                  <input
                    type="email"
                    placeholder="Email"
                    className={`input input-bordered input-secondary flex-grow lg:input-lg input-md`}
                  />
                </label>
              </div>

              <div className="form-control w-full">
                <label className="input-group lg:input-group-lg input-group-md">
                  <span>
                    <GoKey size={30} />
                  </span>
                  <input
                    type="password"
                    placeholder="Password"
                    className={`input input-bordered input-secondary flex-grow lg:input-lg input-md`}
                  />
                </label>
              </div>
              <Link href="/dashboard" passHref>
                <button className="btn btn-primary w-full md:btn-lg">
                  Login
                  <FaRegArrowAltCircleRight size={24} className="ml-2" />
                </button>
              </Link>

              {/* <div className="card-actions">
            </div> */}
            </div>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Powered by{' '}
                <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              </a>
            </footer> */}
    </div>
  );
};

export default Home;
